config/routes.rb
Rails.application.routes.draw do
  get 'scoreboard/index'

  resources :problem_sets do
    resources :solutions
  end
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "scoreboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem_set.rb
class ProblemSet < ApplicationRecord
  has_one_attached :file
  has_many :solutions, dependent: :destroy
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :problem_set
  belongs_to :user
  has_one_attached :file
  has_one_attached :program

  after_create :save_score

  private
  def save_score
    result = Scorer.test(problem_set.file.download, file.download)
    if result.class == Integer
      self.score = result 
    else
      self.score = -42
      self.error = result
    end
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :solutions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/problem_sets_controller.rb
class ProblemSetsController < ApplicationController
  before_action :check_admin, except: :index

  def index
    @problem_sets = ProblemSet.all
  end

  def new
    @problem_set = ProblemSet.new
  end

  def create
    @problem_set = ProblemSet.new
    @problem_set.file.attach(params[:problem_set][:file])
    @problem_set.name = @problem_set.file.filename.to_s
    if @problem_set.save
      redirect_to problem_sets_path
    else
      render :new
    end
  end

  private

  def check_admin
    redirect_to root_path unless current_user.admin
  end
end

app/controllers/scoreboard_controller.rb
class ScoreboardController < ApplicationController
  def index
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :get_problem_set

  def index
  end

  def new
    @solution = Solution.new(user: current_user, problem_set: @problem_set)
  end

  def create
    @solution = Solution.new(user: current_user, problem_set: @problem_set)
    @solution.file.attach(params[:solution][:file])
    @solution.program.attach(params[:solution][:program])
    if @solution.save
      redirect_to scoreboard_index_path
    else
      render :new
    end
  end

  def show

  end

  private

  def get_problem_set
    @problem_set = ProblemSet.find(params[:problem_set_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problem_sets_helper.rb
module ProblemSetsHelper
end

app/helpers/scoreboard_helper.rb
module ScoreboardHelper
end

app/helpers/solution_helper.rb
module SolutionHelper
end

app/views/layouts/_alerts.html.slim
- if !alert.nil?
  .wrapper
    .container
      .col-lg-12
        .alert.alert-dismissible.alert-danger.text-center
          button type="button" class="close" data-dismiss="alert" &times;
          p.alert = alert

- if !notice.nil?
  .wrapper
    .container
      .col-lg-12
        .alert.alert-dismissible.alert-success.text-center
          button type="button" class="close" data-dismiss="alert" &times;
          p.notice = notice

app/views/layouts/_footer.html.slim
hr
.container-fluid.text-center
  span> © LolCode 2019. All Rights Reserved:
  a href='https://www.youtube.com/watch?v=dQw4w9WgXcQ' www..lolcode.com
  span< LolCode
  br
  br
  br

app/views/layouts/application.html.slim
doctype html
html
  head
    title LolCode
    = csrf_meta_tags
    = action_cable_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"
    = stylesheet_link_tag    'application', media: 'all'

    script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"
    = javascript_include_tag 'application'
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"

  body.primary-bg
    .wrapper
      = render 'layouts/navbar/navbar'
      = render 'layouts/alerts'
      .container
        .panel.panel-default
          = yield
          = render 'layouts/footer'

app/views/layouts/navbar/_navbar.html.slim
.navbar.navbar-default
  .container
    .navbar-header
      a.navbar-brand href="#{root_path}" LolCode 2019 Hackerthon
      - unless current_user.nil?
        button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-2'
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar

    .collapse.navbar-collapse id='bs-example-navbar-collapse-2'
      ul.nav.navbar-nav
        li.dropdown
        - if current_user
          li.dropdown
      - unless current_user.nil?
        ul.nav.navbar-nav.navbar-right
          li.dropdown
            a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'  #{current_user.email}
            ul.dropdown-menu role='menu'
              li = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'Log Out'

app/views/problem_sets/create.html.slim
h1 ProblemSets#create
p Find me in app/views/problem_sets/create.html.slim

app/views/problem_sets/index.html.slim
.panel-heading.text-center
  h1 Problem Sets
.panel-body
  - if current_user.admin
    = link_to 'Add New Problem', new_problem_set_path, class: 'btn btn-success pull-right'
    br
  - @problem_sets.each do |ps|
    h2
      u 
        b = ps.name
    br
    span Number of solutions: #{ps.solutions.count}
    br
    span Highest Solution Score: #{ps.solutions.order(score: :asc).first&.score}
    br
    span Highest Solution Score Creator: #{ps.solutions.order(score: :asc).first&.user&.name}
    br
    = link_to "Download Problem Set", rails_blob_path(ps.file, disposition: "attachment"), class: 'btn btn-xs btn-success'

app/views/problem_sets/new.html.slim
h1 Upload new problem set

= form_for @problem_set, url: problem_sets_path do |f|
  span Attach problem: <br>
  = f.file_field :file
  br
  = f.submit

app/views/scoreboard/index.html.slim
.panel-heading.text-center
  h1 Solutions:
.panel-body.text-center
  .col-sm-6
    - endtime = DateTime.parse('2019/03/21 17:00:00').utc
    - if ( endtime - Time.now).positive?
      span.btn.btn-default.disabled Hackathon ends in #{distance_of_time_in_words(endtime - Time.now)}...
    - else
      span.btn.btn-failure.disabled Hackathon is over... :) 
  .col-sm-6
    = link_to "View Problem Sets", problem_sets_path, class: 'btn btn-info'
  br
  br
  - ProblemSet.all.each do |problem_set|
    h2
      b
        u #{problem_set.name}:
    - if ( endtime - Time.now).positive?
      = link_to "Upload New Solution", new_problem_set_solution_path(problem_set_id: problem_set), class: 'btn btn-xs btn-success'

    br
    br
    table.table.table-hover.table-responsive.table-bordered
      tr
        td Submitted At
        td User
        td Points
        td Error (If Any)
      - if problem_set.solutions.count.zero?
        p No Solution Submitted Yet!
      - else
          - problem_set.solutions.order(score: :desc).each do |solution|
            tr
              - if solution.error
                td #{solution.created_at}
                td #{solution.user.name}
                td #{solution.score} points. 
                td #{solution.error}
              - else
                td #{solution.created_at}
                td #{solution.user.name}
                td #{solution.score} points.
                td

app/views/solutions/create.html.slim
h1 Solution#create
p Find me in app/views/solution/create.html.slim

app/views/solutions/index.html.slim
h1 Solution#index
p Find me in app/views/solution/index.html.slim

app/views/solutions/new.html.slim
.panel-heading.text-center
  h1 Upload new solution for "#{@solution.problem_set.name}"
.panel-body
  .row
    .col-sm-4
    .col-sm-4
      .panel-default
          = form_for @solution, url: problem_set_solutions_path do |f|
            h4 
              u Attach solution:
            p Attach your solution:
            = f.file_field :file
            p Attach your program:
            = f.file_field :program
            br
            = f.submit
    .col-sm-4